# ==================================================
# Pywal Integration
# ==================================================
include ~/.cache/wal/colors-kitty.conf

# ==================================================
# Cursor
# ==================================================
cursor_trail 1
cursor_shape beam
cursor_beam_thickness 4
cursor_stop_blinking_after 0
cursor_shape_unfocused unchanged
cursor_blink_interval 0.5

# ==================================================
# Font
# ==================================================
font_family      JetBrainsMono Nerd Font
font_size 11.0
bold_font auto
italic_font auto
bold_italic_font auto

# ==================================================
# Window
# ==================================================
window_padding_width 25
background_opacity 0.9
remember_window_size yes
placement_strategy center
confirm_os_window_close 0

# ==================================================
# Theme
# ==================================================
include current-theme.conf
include adwaitadark.conf
